postgres:
  image: sameersbn/postgresql:9.4-11
  ports:
    - 5439:5432
  environment:
    - PG_TRUST_LOCALNET=true
    - PG_PASSWORD=postgres
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_NAME=hugs_test
